# Generated by Django 5.0.2 on 2024-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pays',
            field=models.CharField(default='', max_length=255),
        ),
    ]
